version: "3"

networks:
  main:

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - main
    ports:
      - 8081:8081
    volumes:
      - ./app:/app
    # env_file:
    #   - ${APP_ENV}
    # command: >
    #   /bin/bash -c "
    #   if [ "${RELOAD}" == "true" ]; then
    #     /start-reload.sh
    #   else
    #     /start.sh
    #   fi"